#Github workflow to add issues and pull requests to project
#
#SPDX-FileCopyrightText: 2023 Birger Schacht
#SPDX-License-Identifier: MIT

# Based on https://stackoverflow.com/questions/64407333/using-github-actions-to-automatically-update-the-repos-submodules

name: Update submodules

on:
  # Allows you to run this workflow manually from the Actions tab or through HTTP API
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    name: 'Submodules Sync'
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
        token: ${{ secrets.GITHUB_TOKEN }}

    # Update references
    - name: Git Sumbodule Update
      run: |
        git submodule update apis-ontologies
        #git submodule foreach 'git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*" && git fetch origin && git checkout origin/main'

    - name: Commit update
      run: |
        git config --global user.name 'Git bot'
        git config --global user.email 'bot@noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"

